FROM node:20-alpine3.20
WORKDIR /app
COPY ./apps/frontend/ ./
RUN apk update && apk upgrade --no-cache
RUN npm install
RUN npm audit fix --force || true
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start"]
